package eu.whrl.aottracegen;

public enum LiteralPoolType {
	RETURN_HANDLER,
	STATIC_FIELD,
	DPC_OFFSET,
	INVOKE_METHOD_PREDICTED_CHAIN_HANDLER,
	JIT_TO_PATCH_PREDICTED_CHAIN_HANDLER,
	INVOKE_METHOD_NO_OPT_HANDLER,
	AOT_DEBUG_FUNCTION
}