package eu.whrl.aottracegen;

public enum LiteralPoolType {
	RETURN_HANDLER,
	CLASS_POINTER,
	STRING_POINTER,
	STATIC_FIELD,
	STATIC_METHOD,
	DIRECT_METHOD,
	SUPERQUICK_METHOD,
	DPC_OFFSET,
	INVOKE_METHOD_PREDICTED_CHAIN_HANDLER,
	JIT_TO_PATCH_PREDICTED_CHAIN_HANDLER,
	INVOKE_METHOD_NO_OPT_HANDLER,
	INVOKE_METHOD_CHAIN_HANDLER,
	INVOKE_METHOD_NATIVE_HANDLER,
	AOT_DEBUG_COUNTER_FUNCTION,
	AOT_DEBUG_LOG_MESSAGE_FUNCTION,
	CALL_AOT_INVOKE_SINGLETON_NATIVE,
	CALL_AOT_INVOKE_SINGLETON_JAVA,
	CALL_AOT_INVOKE_VIRTUAL_QUICK,
	CALL_AOT_INVOKE_INTERFACE,
	CALL_INSTANCEOF_NON_TRIVIAL,
	CALL_ALLOC_OBJECT,
	EXECUTE_INLINE
}