package eu.whrl.aottracegen;

public enum LiteralPoolType {
	RETURN_HANDLER,
	STATIC_FIELD,
	STATIC_METHOD,
	DPC_OFFSET,
	INVOKE_METHOD_PREDICTED_CHAIN_HANDLER,
	JIT_TO_PATCH_PREDICTED_CHAIN_HANDLER,
	INVOKE_METHOD_NO_OPT_HANDLER,
	INVOKE_METHOD_CHAIN_HANDLER,
	INVOKE_METHOD_NATIVE_HANDLER,
	AOT_DEBUG_COUNTER_FUNCTION,
	AOT_DEBUG_LOG_MESSAGE_FUNCTION,
	CALL_AOT_INVOKE_STATIC_NATIVE,
	EXECUTE_INLINE
}